apiVersion: v1
kind: ConfigMap
metadata:
  name: pelagodb-config
data:
  PELAGO_SITE_ID: "1"
  PELAGO_SITE_NAME: "us-east-1"
  PELAGO_LISTEN_ADDR: "0.0.0.0:27615"
  PELAGO_FDB_CLUSTER: "/etc/pelago/fdb.cluster"
  PELAGO_DEFAULT_DATABASE: "qi"
  PELAGO_DEFAULT_NAMESPACE: "core.showA"
  PELAGO_AUTH_REQUIRED: "true"
  PELAGO_AUDIT_ENABLED: "true"
  PELAGO_CACHE_ENABLED: "true"
  PELAGO_CACHE_PROJECTOR_BATCH_SIZE: "1000"
  PELAGO_REPLICATION_DATABASE: "qi"
  PELAGO_REPLICATION_NAMESPACE: "core.showA"
  PELAGO_REPLICATION_BATCH_SIZE: "512"
  PELAGO_REPLICATION_POLL_MS: "300"
  PELAGO_REPLICATION_LEASE_ENABLED: "true"
  PELAGO_REPLICATION_LEASE_TTL_MS: "10000"
  PELAGO_REPLICATION_LEASE_HEARTBEAT_MS: "2000"
