{{- if .Values.operator.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "pelago-operator.fullname" . }}-mutating
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "pelago-operator.fullname" . }}-webhook-cert
  {{- end }}
webhooks:
  - name: mutate.pelagosites.pelago.pelagodb.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: {{ .Values.webhook.failurePolicy.mutating }}
    matchPolicy: Equivalent
    timeoutSeconds: 10
    rules:
      - apiGroups: ["pelago.pelagodb.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pelagosites"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "pelago-operator.fullname" . }}-webhook
        path: /mutate
        port: {{ .Values.webhook.service.port }}
      {{- if not .Values.certManager.enabled }}
      caBundle: {{ .Values.webhook.caBundle | default "" | quote }}
      {{- end }}
{{- end }}
